[package]
name = "generate_permutations"
version = "0.1.0"
authors = ["Jan Marthedal Rasmussen <jan@janmr.com>"]
edition = "2018"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmark"
harness = false
